version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_simple
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tienda
    ports:
      - "5437:5432"
